import { LayoutInputInterface } from '../src/interface/layout';

const spaces = (size: number, value = ''): string => (value || '').padEnd(size, ' ').substring(0, size);
const zeros = (size: number, value = ''): string => (value || '').padStart(size, '0').substring(0, size);

// { key : 'type(size), defaultValue', ... } or [ 'key, type(size), defaultValue', ... ]
export const cnab500HeaderRemessa = {
    id_registro: '9(1), 0',
    id_remessa: '9(1), 1',
    literal_remessa: 'X(7), REM.TST',
    cod_servico: '9(2), 1',
    literal_servico: 'X(15), COBRANCA',
    cod_empresa: '9(20), 1',
    nome_empresa: 'X(30), EMPRESA TESTE',
    cod_banco: '9(3), 341',
    nome_banco: 'X(15), PAULISTA S.A.',
    data_gravacao: '9(6), 0',
    brancos_01: 'X(8)',
    id_sistema: 'X(2)',
    seq_arquivo: '9(7), 1',
    brancos_02: 'X(377)',
    seq_registro: '9(6), 1',
};

export const cnab500HeaderJsonSample = {
    id_registro: '0',
    id_remessa: '1',
    literal_remessa: 'REMXX.TST',
    cod_servico: '2',
    literal_servico: 'COBRANCA',
    cod_empresa: '3',
    nome_empresa: 'GOOGLE',
    cod_banco: '444',
    nome_banco: 'PAULISTA S.A.',
    data_gravacao: '290924',
    id_sistema: 'XY',
    seq_arquivo: '5',
    seq_registro: '6',
};

export const cnab500HeaderTextSample = [
    zeros(1, cnab500HeaderJsonSample.id_registro),
    zeros(1, cnab500HeaderJsonSample.id_remessa),
    spaces(7, cnab500HeaderJsonSample.literal_remessa),
    zeros(2, cnab500HeaderJsonSample.cod_servico),
    spaces(15, cnab500HeaderJsonSample.literal_servico),
    zeros(20, cnab500HeaderJsonSample.cod_empresa),
    spaces(30, cnab500HeaderJsonSample.nome_empresa),
    zeros(3, cnab500HeaderJsonSample.cod_banco),
    spaces(15, cnab500HeaderJsonSample.nome_banco),
    zeros(6, cnab500HeaderJsonSample.data_gravacao),
    spaces(8),
    spaces(2, cnab500HeaderJsonSample.id_sistema),
    zeros(7, cnab500HeaderJsonSample.seq_arquivo),
    spaces(377),
    zeros(6, cnab500HeaderJsonSample.seq_registro),
].join('');

// console.log(cnab500HeaderTextSample);

export const cnab500DetalheRemessaTipo1 = {
    id_registro: '9(1), 1',
    brancos_01: 'X(19)',
    coobrigacao: '9(2)',
    caracteristica_especial: 'X(2)',
    modalidade_operacao: '9(4)',
    natureza_operacao: '9(2)',
    origem_recurso: '9(4)',
    classificacao_risco: 'X(2)',
    brancos_02: '9(1)',
    numero_controle_participante: 'X(25)',
    branco_03: '9(8)',
    id_titulo_banco: 'X(11)',
    digito_verificador_banco: 'X(1)',
    valor_pago: '9(10)',
    brancos_04: '9(2)',
    data_liquidacao: '9(6)',
    brancos_05: 'X(8)',
    id_ocorrencia: '9(2)',
    numero_documento: 'X(10)',
    data_vencimento: '9(6)',
    valor_titulo: '9(13)',
    brancos_06: '9(8)',
    especie: '9(2)',
    faixa_risco: 'X(1)',
    data_prevista: '9(6)',
    brancos_07: '9(3)',
    tipo_pessoa_cedente: 'X(2)',
    brancos_08: '9(12)',
    numero_termo_cessao: 'X(19)',
    valor_presente: '9(13)',
    valor_abatimento: '9(13)',
    id_tipo_inscricao_sacado: '9(2)',
    numero_inscricao_sacado: '9(14)',
    nome_sacado: 'X(40)',
    endereco_sacado: 'X(40)',
    brancos_09: 'X(12)',
    cep_sacado: '9(8)',
    cedende: 'X(60)',
    taxa_juros_mensal: '9(8)',
    juros_mora: '9(8)',
    multa: '9(13)',
    valor_baixa_acordo: '9(13)',
    data_baixa_acordo: '9(6)',
    brancos_10: 'X(52)',
    seq_registro: '9(6)',
};

export const cnab500DetalheTipo1JsonSample = {
    id_registro: '1',
    coobrigacao: '3',
    caracteristica_especial: '4',
    modalidade_operacao: '5',
    natureza_operacao: '6',
    origem_recurso: '7',
    classificacao_risco: '8',
    numero_controle_participante: '10',
    id_titulo_banco: '12',
    digito_verificador_banco: '9',
    valor_pago: '14',
    data_liquidacao: '16',
    id_ocorrencia: '18',
    numero_documento: '19',
    data_vencimento: '20',
    valor_titulo: '21',
    especie: '23',
    faixa_risco: '2',
    data_prevista: '25',
    tipo_pessoa_cedente: '27',
    numero_termo_cessao: '29',
    valor_presente: '30',
    valor_abatimento: '31',
    id_tipo_inscricao_sacado: '32',
    numero_inscricao_sacado: '33',
    nome_sacado: '34',
    endereco_sacado: '35',
    cep_sacado: '37',
    cedende: '38',
    taxa_juros_mensal: '39',
    juros_mora: '40',
    multa: '41',
    valor_baixa_acordo: '42',
    data_baixa_acordo: '43',
    seq_registro: '45',
};

export const cnab500DetalheTipo1TextSample = [
    zeros(1, cnab500DetalheTipo1JsonSample.id_registro),
    spaces(19),
    zeros(2, cnab500DetalheTipo1JsonSample.coobrigacao),
    spaces(2, cnab500DetalheTipo1JsonSample.caracteristica_especial),
    zeros(4, cnab500DetalheTipo1JsonSample.modalidade_operacao),
    zeros(2, cnab500DetalheTipo1JsonSample.natureza_operacao),
    zeros(4, cnab500DetalheTipo1JsonSample.origem_recurso),
    spaces(2, cnab500DetalheTipo1JsonSample.classificacao_risco),
    zeros(1),
    spaces(25, cnab500DetalheTipo1JsonSample.numero_controle_participante),
    zeros(8),
    spaces(11, cnab500DetalheTipo1JsonSample.id_titulo_banco),
    spaces(1, cnab500DetalheTipo1JsonSample.digito_verificador_banco),
    zeros(10, cnab500DetalheTipo1JsonSample.valor_pago),
    zeros(2),
    zeros(6, cnab500DetalheTipo1JsonSample.data_liquidacao),
    spaces(8),
    zeros(2, cnab500DetalheTipo1JsonSample.id_ocorrencia),
    spaces(10, cnab500DetalheTipo1JsonSample.numero_documento),
    zeros(6, cnab500DetalheTipo1JsonSample.data_vencimento),
    zeros(13, cnab500DetalheTipo1JsonSample.valor_titulo),
    zeros(8),
    zeros(2, cnab500DetalheTipo1JsonSample.especie),
    zeros(1, cnab500DetalheTipo1JsonSample.faixa_risco),
    zeros(6, cnab500DetalheTipo1JsonSample.data_prevista),
    zeros(3),
    zeros(2, cnab500DetalheTipo1JsonSample.tipo_pessoa_cedente),
    zeros(12),
    spaces(19, cnab500DetalheTipo1JsonSample.numero_termo_cessao),
    zeros(13, cnab500DetalheTipo1JsonSample.valor_presente),
    zeros(13, cnab500DetalheTipo1JsonSample.valor_abatimento),
    zeros(2, cnab500DetalheTipo1JsonSample.id_tipo_inscricao_sacado),
    zeros(14, cnab500DetalheTipo1JsonSample.numero_inscricao_sacado),
    spaces(40, cnab500DetalheTipo1JsonSample.nome_sacado),
    spaces(40, cnab500DetalheTipo1JsonSample.endereco_sacado),
    spaces(12),
    zeros(8, cnab500DetalheTipo1JsonSample.cep_sacado),
    spaces(60, cnab500DetalheTipo1JsonSample.cedende),
    zeros(8, cnab500DetalheTipo1JsonSample.taxa_juros_mensal),
    zeros(8, cnab500DetalheTipo1JsonSample.juros_mora),
    zeros(13, cnab500DetalheTipo1JsonSample.multa),
    zeros(13, cnab500DetalheTipo1JsonSample.valor_baixa_acordo),
    zeros(6, cnab500DetalheTipo1JsonSample.data_baixa_acordo),
    spaces(52),
    zeros(6, cnab500DetalheTipo1JsonSample.seq_registro),
].join('');

export const cnab500TraillerRemessa = ['id_registro, 9(1), 9', 'brancos_01, X(493)', 'seq_registro, 9(6)'];

export const cnab500TraillerJsonSample = {
    id_registro: '9',
    seq_registro: '999',
};

export const cnab500TraillerTextSample = [
    zeros(1, cnab500TraillerJsonSample.id_registro),
    spaces(493),
    zeros(6, cnab500TraillerJsonSample.seq_registro),
].join('');

export const cnab500: LayoutInputInterface = {
    size: 500,
    lines: {
        header: {
            layout: cnab500HeaderRemessa,
        },
        detalhes: {
            segments: {
                tipo_1: {
                    layout: cnab500DetalheRemessaTipo1,
                },
            },
        },
        trailler: {
            layout: cnab500TraillerRemessa,
        },
    },
};
