import { LayoutInputInterface } from '../src/interface/layout';

export const itau240Header = {
    // "coluna": "direction, size, defaultValue, fill, position",
    codigo_banco: 'R, 1, 341, "", 3',
    lote_servico: 'R, 4, "", "", 4',
    tipo_registro: 'R, 1, "", "", 8',
    brancos_01: 'L, 9, "", "", 9',
    tipo_inscricao: 'R, 1, "", "", 18',
    inscricao_numero: 'R, 14, "", "", 19',
    brancos_02: 'L, 20, "", "", 33',
    zeros_01: 'R, 1, "", "", 53',
    agencia: 'R, 4, "", "", 54',
    brancos_03: 'L, 1, "", "", 58',
    zeros_02: 'R, 7, "", "", 59',
    conta: 'R, 5, "", "", 66',
    brancos_04: 'L, 1, "", "", 71',
    dac: 'R, 1, "", "", 72',
    nome_empresa: 'L, 30, "", "", 73',
    nome_banco: 'L, 30, "BANCO ITAU SA", "", 103',
    brancos_05: 'L, 10, , ,133',
    codigo_arquivo: 'R, 1, "1", "", 143',
    data_geracao: 'R, 8, "", "", 144',
    hora_geracao: 'R, 6, "", "", 152',
    numero_sequencial_arquivo_retorno: 'R, 6, "", "", 158',
    versao_layout_arquivo: 'R, 3, "040", "", 164',
    zeros_03: 'R, 5, "", "", 167',
    brancos_06: 'L, 54, "", "", 172',
    zeros_04: 'R, 3, "", "", 226',
    brancos_07: 'L, 12, "", "", 229',
};

const segmento_p = {
    codigo_banco: 'R, 3, "341", "", 1',
    lote_servico: 'R, 4, "", "", 4',
    tipo_registro: 'R, 1, "3", "", 8',
    numero_sequencial_registro_lote: 'R, 5, "", "", 9',
    segmento: 'L, 1, "P", "", 14',
    brancos_01: 'L, 1, "", "", 15',
    codigo_ocorrencia: 'R, 2, "", "", 16',
    zeros_01: 'R, 1, "", "", 18',
    agencia: 'R, 4, "", "", 19',
    brancos_02: 'L, 1, "", "", 23',
    zeros_02: 'R, 7, "", "", 24',
    conta: 'R, 5, "", "", 31',
    brancos_03: 'L, 1, "", "", 36',
    dac: 'R, 1, "", "", 37',
    carteira: 'R, 3, "", "", 38',
    nosso_numero: 'R, 8, "", "", 41',
    dac_nosso_numero: 'R, 1, "", "", 49',
    brancos_04: 'L, 8, "", "", 50',
    zeros_03: 'R, 5, "", "", 58',
    numero_documento: 'L, 10, "", "", 63',
    brancos_05: 'L, 5, "", "", 73',
    vencimento: 'R, 8, "", "", 78',
    valor_titulo: 'R, 15, "", "", 86',
    agencia_cobradora: 'R, 5, "", "", 101',
    dac_agencia_cobradora: 'R, 1, "", "", 106',
    especie: 'R, 2, "", "", 107',
    aceite: 'L, 1, "N", "", 109',
    data_emissao: 'R, 8, "", "", 110',
    zeros_04: 'R, 1, "", "", 118',
    data_juros_mora: 'R, 8, "", "", 119',
    juros_1_dia: 'R, 15, "", "", 127',
    zeros_05: 'R, 1, "", "", 142',
    data_1o_desconto: 'R, 8, "", "", 143',
    valor_1o_desconto: 'R, 15, "", "", 151',
    valor_iof: 'R, 15, "", "", 166',
    valor_abatimento: 'R, 15, "", "", 181',
    identificacao_titulo_empresa: 'L, 25, "", "", 196',
    codigo_negativacao_protesto: 'R, 1, "", "", 221',
    prazo_negativacao_protesto: 'R, 2, "", "", 222',
    codigo_baixa: 'R, 1, "", "", 224',
    prazo_baixa: 'R, 2, "", "", 225',
    zeros_06: 'R, 13, "", "", 227',
    brancos_06: 'L, 1, "", "", 240',
};

export const itau240: LayoutInputInterface = {
    size: 240,
    lines: {
        header: {
            layout: itau240Header,
        },
        detalhes: {
            segments: {
                segmento_p: {
                    layout: segmento_p,
                },
            },
        },
    },
};
