import { LayoutInputInterface } from '../src/interface/layout';
import { generateData } from './generator.test';

const header_arquivo = {
    _id_line: '9(1)!',
    _id_segment: '9(1)',
    cod_banco: '9(3), "341"',
    lote_servico: '9(4)',
    tipo_registro: '9(1)',
    brancos_01: 'X(9)',
    tipo_inscricao: '9(1)',
    inscricao_numero: '9(14)',
    brancos_02: 'X(20)',
    zeros_01: '9(1)',
    agencia: '9(4)',
    brancos_03: 'X(1)',
    zeros_02: '9(7)',
    conta: '9(5)',
    brancos_04: 'X(1)',
    dac: '9(1)',
    nome_empresa: 'X(30)',
    nome_banco: 'X(30), "BANCO ITAU SA"',
    brancos_05: 'X(10)',
    codigo_arquivo: '9(1)',
    data_geracao: '9(8)',
    hora_geracao: '9(6)',
    numero_sequencial_arquivo_retorno: '9(6)',
    versao_layout_arquivo: '9(3),"040"',
    zeros_03: '9(5)',
    brancos_06: 'X(54)',
    zeros_04: '9(3)',
    brancos_07: 'X(12)',
};

export const { json: itau_header_arquivo_json, line: itau_header_arquivo_line } = generateData(header_arquivo, {
    _id_line: '0',
    _id_segment: '1',
});

const header_lote = {
    _id_line: '9(1)!',
    _id_segment: '9(1)',
    cod_banco: '9(3), "341"',
    lote_servico: '9(4)',
    tipo_registro: '9(1),3',
    tipo_operacao: 'X(1)',
    tipo_servico: '9(2),1',
    zeros_01: '9(2)',
    numero_versao_layout_lote: '9(3), "030"',
    brancos_01: 'X(1)',
    tipo_inscricao: '9(1)',
    inscricao_numero: '9(15)',
    brancos_02: '9(20)',
    zeros_02: '9(1)',
    agencia: '9(4)',
    brancos_03: 'X(1)',
    zeros_03: '9(7)',
    conta: '9(5)',
    brancos_04: 'X(1)',
    dac: '9(1)',
    nome_empresa: 'X(30)',
    brancos_05: 'X(80)',
    numero_sequencial_arquivo_retorno: '9(8)',
    data_gravacao: '9(8)',
    data_credito: '9(8)',
    brancos_06: 'X(33)',
};

const trailer_lote = {
    _id_line: '9(1)!',
    _id_segment: '9(1)',
    cod_banco: '9(3), "341"',
    lote_servico: '9(4)',
    tipo_registro: '9(1), "5"',
    brancos_01: 'X(9)',
    quantidade_registros: '9(6)',
    quantidade_titulos_cobranca_simples: '9(6)',
    valor_total_titulos_cobranca_simples: '9(17)',
    quantidade_titulos_cobranca_vinculada: '9(6)',
    valor_total_titulos_cobranca_vinculada: '9(17)',
    zeros_01: '9(46)',
    aviso_bancario: 'X(8)',
    brancos_02: 'X(117)',
};

const trailer_arquivo = {
    _id_line: '9(1)!',
    _id_segment: '9(1)',
    cod_banco: 'X(3), "341"',
    lote_servico: '9(4),9999',
    tipo_registro: '9(1), "9"',
    brancos_01: 'X(9)',
    quantidade_lotes: '9(6)',
    quantidade_registros: '9(6)',
    zeros_01: '9(6)',
    brancos_02: 'X(205)',
};

const segmento_p = {
    _id_line: '9(1)!',
    _id_segment: '9(1)',
    cod_banco: 'X(3), "341"',
    lote_servico: '9(4)',
    tipo_registro: '9(1), "3"',
    numero_sequencial_registro_lote: '9(5)',
    segmento: 'X(1), "P"',
    brancos_01: 'X(1)',
    codigo_ocorrencia: '9(2)',
    zeros_01: '9(1)',
    agencia: '9(4)',
    brancos_02: 'X(1)',
    zeros_02: '9(7)',
    conta: '9(5)',
    brancos_03: 'X(1)',
    dac: '9(1)',
    carteira: '9(3)',
    nosso_numero: '9(8)',
    dac_nosso_numero: '9(1)',
    brancos_04: 'X(8)',
    zeros_03: '9(5)',
    numero_documento: 'X(10)',
    brancos_05: 'X(5)',
    vencimento: '9(8)',
    valor_titulo: '9(15)',
    agencia_cobradora: '9(5)',
    dac_agencia_cobradora: '9(1)',
    especie: '9(2)',
    aceite: 'X(1)',
    data_emissao: '9(8)',
    zeros_04: '9(1)',
    data_juros_mora: '9(8)',
    juros_1_dia: '9(15)',
    zeros_05: '9(1)',
    data_1o_desconto: '9(8)',
    valor_1o_desconto: '9(15)',
    valor_iof: '9(15)',
    valor_abatimento: '9(15)',
    identificacao_titulo_empresa: 'X(25)',
    codigo_negativacao_protesto: '9(1)',
    prazo_negativacao_protesto: '9(2)',
    codigo_baixa: '9(1)',
    prazo_baixa: '9(2)',
    zeros_06: '9(13)',
    brancos_06: 'X(1)',
};

export const itau240: LayoutInputInterface = {
    size: 242,
    idLine: [0, 1],
    idSegment: [1, 1],
    autoIdentification: true,
    lines: {
        header_arquivo: {
            id: '0',
            layout: header_arquivo,
        },
        header_lote: {
            id: '1',
            layout: header_lote,
        },
        detalhes: {
            id: '3',
            segments: {
                segmento_p: {
                    id: 'P',
                    layout: segmento_p,
                },
            },
        },
        trailer_lote: {
            id: '5',
            layout: trailer_lote,
        },
        trailer_arquivo: {
            id: '9',
            layout: trailer_arquivo,
        },
    },
};
