export const errorPrefix = 'CNAB';

export const ERROR_CODE = {
    LAYOUT_INVALID: 1,
    LAYOUT_LINES_INVALID: 2,
    LAYOUT_LINE_INVALID: 3,
    COLUMN_TYPE_INVALID: 4,
    COLUMN_DIRECTION_INVALID: 5,
    COLUMN_TYPE_SIZE_INVALID: 6,
    COLUMN_KEY_INVALID: 7,
    COLUMN_DATA_MISSING: 8,
    COLUMN_LAYOUT_ENTRY_INVALID: 9,
    COLUMN_LAYOUT_NOT_FOUND: 10,
    COLUMN_CONFIG_INVALID: 11,
    LINE_LENGTH_INVALID: 12,
    COLUMN_POSITION_INVALID: 13,
    COLUMN_VALUE_UNDEFINED: 14,
    COLUMN_VALUE_NULL: 15,
    COLUMN_VALUE_EMPTY: 16,
    COLUMN_VALUE_BIGGER_SIZE: 17,
    COLUMNS_CONFIG_MISSING: 18,
    COLUMNS_CONFIG_INVALID: 19,
    ID_POSITION_CONFIG_INVALID: 20,
    ID_FIELD_NOT_FOUND: 21,
    ID_LINE_NOT_FOUND: 22,
    ID_SEGMENT_NOT_FOUND: 25,
    ID_LINE_MISSING: 26,
    ID_SEGMENT_MISSING: 27,
    ID_AUTO_IDENTIFICATION_INVALID: 23,
    UNKNOWN: 0,
};

export type ERROR_CODE = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
