export const errorPrefix = 'CNAB';

export const ERROR_CODE = {
    LAYOUT_INVALID: 1,
    LAYOUT_LINES_INVALID: 2,
    LAYOUT_LINE_INVALID: 3,
    COLUMN_TYPE_INVALID: 4,
    COLUMN_DIRECTION_INVALID: 5,
    COLUMN_TYPE_SIZE_INVALID: 6,
    COLUMN_KEY_INVALID: 7,
    COLUMN_DATA_MISSING: 8,
    COLUMN_LAYOUT_ENTRY_INVALID: 9,
    COLUMN_LAYOUT_NOT_FOUND: 10,
    COLUMN_CONFIG_INVALID: 11,
    LINE_LENGTH_INVALID: 12,
    COLUMN_POSITION_INVALID: 13,
    COLUMN_VALUE_UNDEFINED: 14,
    COLUMN_VALUE_EMPTY: 15,
    COLUMN_VALUE_BIGGER_SIZE: 16,
    UNKNOWN: 0,
};
